[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
environment=TZ="Asia/Maldives"

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
autostart=true
startsecs=5
startretries=3
exitcodes=0
user=nginx

[program:filebeats]
command=php-fpm -y /home/hpapi/api/php-fpm.conf -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
autostart=true
startsecs=5
startretries=3
exitcodes=0
user=nginx

[eventlistener:quit_on_failure]
command=sh -c 'while read line; do kill -TERM $PPID; done < /dev/stdin'
events=PROCESS_STATE_FATAL,PROCESS_STATE_EXITED
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
